name: Laravel Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install PHP 8.2
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Check for Composer updates
      id: composer-check
      run: |
        php check-composer.php

    - name: Install Composer dependencies if updates available
      if: steps.composer-check.outputs.exit_code == '0'
      run: |
        curl -sS https://getcomposer.org/installer | php
        php composer.phar install --no-interaction --prefer-dist

    # - name: Copy .env.example to .env
    #   run: cp .env.example .env

    # - name: Generate Laravel application key
    #   run: php artisan key:generate

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # You can specify the version you need

    - name: Install NPM dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Transfer files via SSH
      uses: appleboy/scp-action@master
      with:
        host: 31.170.164.6
        username: u752782537
        password: Coopevemu@2024
        port: 65002
        source: '.'  # Path to your Laravel project
        target: '/home/u752782537/domains/bmglewis.online'  # Destination directory on the server

    - name: Create symbolic link
      uses: appleboy/ssh-action@master
      with:
        host: 31.170.164.6
        username: u752782537
        password: Coopevemu@2024
        port: 65002
        script: |
          ln -s /home/u752782537/domains/bmglewis.online/public /home/u752782537/domains/bmglewis.online/public_html

    - name: SSH into server and run deployment commands
      uses: appleboy/ssh-action@master
      with:
        host: 31.170.164.6
        username: u752782537
        password: Coopevemu@2024
        port: 65002
        script: |
          cd /home/u752782537/domains/bmglewis.online
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          php artisan config:clear
          php artisan route:clear
          php artisan view:clear
